---

hermes_base_url: http://130.238.178.239:9000/api/0.1
hermes_user: dummy_user
hermes_token: my_token

summary_host: testuppmax
summary_user: arteria
summary_host_key: /path/to/ssh/key
summary_destination: /tmp/summaries/
summary_ngi_pipeline_reports_destination: /tmp/summaries/ngi_reports

projman_install_location: /path/to/projman_filler
projman_connection_string: mssql+pymssql://<username>:<password>@<host>/<database>?charset=utf8

biotank_hosts: mm-xart002,mm-xart003
biotank_user: arteria
biotank_user_key: "/path/to/ssh/key"

remote_host: testuppmax
remote_user: arteria
remote_host_key: /path/to/ssh/key
remote_destination: /tmp/runfolders/
remote_sisyphus_location: /opt/arteria/arteria-siswrap-env/deps/sisyphus/sisyphus-latest

ngi_pipeline_url: https://irma1.uppmax.uu.se:4444/ngi_pipeline_upps

irma_api_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaa
irma_remote_path: ./staging/
irma_reports_remote_path: ./staging/reports/
irma_checksum_base_url: https://irma1.uppmax.uu.se:4444/arteria_checksum_staging/api/1.0
irma_siswrap_base_url: https://irma1.uppmax.uu.se:4444/arteria_siswrap_staging/api/1.0
irma_archive_upload_base_url: https://irma1.uppmax.uu.se:4444/arteria_archive_staging/api/1.0
archive_db_base_url: http://mm-xart002:10500/api/1.0/
delivery_service_url: http://some-host.com:9999/

irma_replace_expressions:
 - 's/UPPNEX_PROJECT: a2009002/UPPNEX_PROJECT: ngi2016001/'
 - 's/UPPNEX_QOS: seqver/#UPPNEX_QOS: seqver/'

send_mail_to: example.mail.address@send.errors.to

runfolder_service_port: 10800
bcl2fastq_service_port: 10900
siswrap_service_port: 10700
archive_upload_service_port: 10600

# The service URL polled in the runfolder sensor:
runfolder_svc_urls:
  - http://testarteria1:10800/api/1.0/runfolders/pickup

incoming_svc_urls:
  - url: http://testarteria1:10850/api/1.0/runfolders/next
    dest_folder: /data/testarteria1/runfolders
    remote_user: arteria
    user_key: /home/arteria/.ssh/id_rsa


charon_api_token: dummy_token
charon_base_url: http://charon.url
slack_webhook_url: https://slack.webhook.url

charon_status_report_slack_channel: "#bottest"
check_cert_slack_channel: "#bottest"
delivery_workflow_status_slack_channel: '#bottest'
archive_status_slack_channel: "#bottest"

supr_api_user: apiuser
supr_api_key: apikey
supr_api_url: https://disposer.c3se.chalmers.se/supr-test/api
